// <auto-generated />
using Microservices.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Microservices.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microservices.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLocalPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Computer",
                            Description = "Keyboard description",
                            ImageUrl = "https://m.media-amazon.com/images/I/61jPovnNr-L._AC_SL1200_.jpg",
                            Name = "Keyboard",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Computer",
                            Description = "Mouse description",
                            ImageUrl = "https://productimages.hepsiburada.net/s/468/550/110000506050793.jpg/format:webp",
                            Name = "Mouse",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Computer",
                            Description = "Motherboard description",
                            ImageUrl = "https://dlcdnwebimgs.asus.com/gain/fdae2676-06f0-41e4-a184-8547aedb3b9c/w692",
                            Name = "Motherboard",
                            Price = 10.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
